site_name: 'Documentation Template'
repo_url: https://github.com/harness-idp-sandbox/morningstar-engrjava01
edit_uri: https://github.com/harness-idp-sandbox/morningstar-engrjava01/blob/main/docs/index.md

nav:
  - Home: index.md

plugins:
  - techdocs-core